# Ruta base
ruta_base: "/content/tfm-oepia" # Ruta base del proyecto

# Configuracion de los Logs
logs_config:
  ruta_salida_logs: "Logs" # Ruta de los logs partiendo de la Ruta base
  format: "%(asctime)s - %(levelname)s - %(message)s" # Formato de logs
  level: "INFO" # Modalidad de los logs

# Configuracion de la Base de Datos de Mensajes (Contexto)
sesiones:
  ruta: "Sesiones" # Ruta despliegue módulo sesiones partiendo ruta base
  ruta_db: "datos" # Ruta donde almacenar la base de datos de sesiones partiendo RutaBase+RutaSesiones
  nombre_db: "sesiones.sqlite" # Nombre base de datos de sesiones
  tabla: "sesiones" # Nombre tabla de sesiones

# Configuracion de Base de Datos Vectorial
vectorial_database:
  enabled_ingest: 1 # Habilitado: 1 Deshabilitado: 0
  ruta: "FaissOPEIA" # Ruta despliegue Módulo base de datos vectorial RAG
  serialized_database: "db" # Ruta almacenamiento datos serializados RAG partiendo RutaBase+RutaModuloRAG
  file_retriever: "retriever.pkl" # Nombre del fichero de datos serializados Retriever
  file_vector_index: "bbdd_vecrtorial.pkl" # Nombre del fichero datos serializados bbdd_vectorial
  parameters_tokenizador:
    name_model_llm: llama3 # Nombre modelo LLM general
    name_model_tokenizador: llama3 # Nombre modelo LLM tokenizador
    return_tensors: pt # Formato de tensor pt -> pytorch
    max_length: 1024 # Tamaño máximo de tokens a alamacenar por bloque
    truncation: true # Truncado True <- SI
    padding: max_length # Tipo de relleno: Tamaño máximo (max_length)
    temperature: 0.0 # Temperatura: 0 -> No es creativa

# WebScrapping
scrapping:
  enabled_scapping: 1 # 1: Habilitado 0: Deshabilitado
  ruta: "ObtencionDatos" # Ruta de despliegue del modulo de WebScrapping
  descarga_datos: "datos" # Ruta de almacenamiento de datos
  dataset_index:
    campos_metadata: # Campos dataset metadata
      - url
    campo_texto: # Campo dataset almacenar BBDD vectorial
      - resumen
  fuentes:
    BOE: # Datos fuente del BOE
      url: "https://www.boe.es/"
      patron: "https://www.boe.es/boe/dias/$anio/$mes/$dia/index.php?s=2B"
      fichero_csv: "csv_boes_oferta_publica"
    BOCYL: # Datos fuente del BOCyL
      url: "https://bocyl.jcyl.es/"
      patron: "https://bocyl.jcyl.es/boletin.do?fechaBoletin=$dia/$mes/$anio#I.B._AUTORIDADES_Y_PERSONAL"
      fichero_csv: "csv_bocyls_oferta_publica"
    limitacion_descargas: 10 # Limitado de descargas
    tiempo_entre_descargas: 1 # Establece un tiempo entre descargas para no saturar ka fuente
    separador: "|" # Separador dentro del CVV generado
  headers:
    accept: "application/xml;q=0.9, */*;q=0.8" # Cabeceras para el agente de webscrapping
  timeout: 10 # Tiempo de vida de la sesion de scrapping
  n_sentences_summary: 10 # Numero de frases del resumen
  max_chunk_length: 512 # Tamaño maximo del resunen


# Modelo LLM principal
llm_oepia:
  ruta: "OEPIA"
  parameters_modelo:
    llm_model: llama3 # Modelo general para las respuestas del ChatBoot
    temperature: 0.0 # 0.0 poco creativo
    nombre_asistente: "OPEIA"


# Agentes
agentePDF:
  ruta: "AgentePDF"
  n_reintentos: 4 # Numero de intentos de ejecucion del agente (tiene que ver con la rapidez del chatBoot)

